### ISSUE TITLE
Seems to stop working in 2023.5

### ISSUE THREAD

**Issue by robertboccia** [evilmarty/mjpeg-timelapse#20]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/mjpeg_timelapse/__init__.py:16
Integration: Mjpeg Timelapse (documentation, issues)
First occurred: 3:23:10 AM (1 occurrences)
Last logged: 3:23:10 AM

Error setting up entry TL S21 for mjpeg_timelapse
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mjpeg_timelapse/__init__.py", line 16, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ardyp87** [comment]
Same issue after HA last release.

**Comment by markaggar** [comment]
Yep, same here, same error on 2023.5.2

**Comment by blinderix** [comment]
Same here, 2023.5.2

**Comment by robertboccia** [comment]
@evilmarty any ideas when a fix is coming?

**Comment by cibernox** [comment]
FWIW, I know what's causing this issue and the fix is very easy. Just apply the same changes I applied on this other integration of mine: https://github.com/cibernox/homeassistant-poolstation/commit/9990a331145a73c98a92b1133dd9066c850be0a4

**Comment by cibernox** [comment]
Ready to be merged

**Comment by evilmarty** [comment]
Thank you @cibernox for your help. I've been too busy to look into this issue. Much appreciated.
